server.port=8080

# JWT Configuration, Shorten access token to 15 minutes
jwt.expiration=900000

# Refresh token lives 7 days
jwt.refresh-expiration=604800000

# App info
spring.application.name=spring-jwt-auth-server

# Show security logs during development
logging.level.org.springframework.security=INFO
